#!/usr/bin/env node
'use strict'
var express = require('express')

var assets = require('./components/assets')
var upload = require('./components/upload')
var test = require('./components/test')

var app = express()

assets.start(app)
upload.start(app)
test.start(app)

app.listen(80, function () {
  console.log('[Server] -- listening localhost:80....'.green)
})