#!/usr/bin/env node
'use strict'
var express = require('express')

var assets = require('./modules/assets')
var upload = require('./modules/upload')
var test = require('./modules/test')

var app = express()

var main = {
  app: app,
  rootDir: __dirname
}

// 启动静态资源访问服务
assets.start(main)
// 启动上传服务
upload.start(main)
// 启动模块测试服务
test.start(main)

app.listen(80, function () {
  console.log('[Server] -- listening localhost:80....'.green)
})